import React from 'react';
import { Box, VStack, Text, Heading, HStack, Divider } from '@chakra-ui/react';

interface MeetingNotesPDFProps {
  title: string;
  description: string;
  participants?: string;
  source?: string;
  projectName?: string;
  activityName?: string;
}

interface MeetingNotesPDFViewerProps extends MeetingNotesPDFProps {
  height?: number;
}

export const MeetingNotesPDFViewer: React.FC<MeetingNotesPDFViewerProps> = ({
  title,
  description,
  participants,
  source,
  projectName,
  activityName,
  height = 600,
}) => {
  const currentDate = new Date().toLocaleDateString();

  return (
    <Box
      width="100%"
      height={`${height}px`}
      bg="white"
      p={8}
      border="1px solid"
      borderColor="gray.200"
      borderRadius="md"
      overflow="auto"
      fontSize="sm"
      lineHeight="1.6"
      fontFamily="Arial, sans-serif"
      style={{ 
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        transform: 'scale(0.9)',
        transformOrigin: 'top left'
      }}
    >
      <VStack spacing={6} align="stretch">
        {/* Header */}
        <VStack spacing={2} align="start">
          <Heading size="lg" color="black" fontWeight="bold">
            {title || 'Meeting Notes'}
          </Heading>
          <Text fontSize="md" color="gray.600" fontWeight="semibold">
            R&D Evidence Documentation
          </Text>
          <VStack spacing={1} align="start" fontSize="xs" color="gray.500">
            <Text>
              Date: {currentDate}
              {projectName && ` • Project: ${projectName}`}
              {activityName && ` • Activity: ${activityName}`}
            </Text>
            {participants && <Text>Participants: {participants}</Text>}
            {source && <Text>Source: {source}</Text>}
          </VStack>
        </VStack>

        <Divider borderColor="black" />

        {/* Content */}
        <VStack spacing={4} align="stretch">
          <Heading size="md" color="gray.800" fontWeight="semibold">
            Meeting Notes
          </Heading>
          <Text 
            color="black" 
            whiteSpace="pre-wrap"
            lineHeight="1.6"
            fontSize="sm"
          >
            {description}
          </Text>
        </VStack>

        {/* Footer */}
        <Box pt={8} mt="auto">
          <Divider borderColor="gray.300" mb={2} />
          <Text fontSize="xs" color="gray.400" textAlign="center">
            Generated by Claude AI for R&D Evidence Documentation
          </Text>
        </Box>
      </VStack>
    </Box>
  );
};